/* Royale Dependency List: */
/**
 * Generated by Apache Royale Compiler from /home/joshua/Development/Haxe/openfl/lib/openfl/system/Capabilities.as
 * openfl.system.Capabilities
 *
 * @fileoverview
 * @externs
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

/** @const */
var openfl = {};
/** @const */
openfl.system = {};

/**
 * @constructor
 */
openfl.system.Capabilities = function() {
};


/**
 * @protected
 * @return {string}
 */
openfl.system.Capabilities.get_cpuArchitecture = function() {
  return null;
};


/**
 * @protected
 * @return {string}
 */
openfl.system.Capabilities.get_language = function() {
  return null;
};


/**
 * @protected
 * @return {string}
 */
openfl.system.Capabilities.get_manufacturer = function() {
  return null;
};


/**
 * @protected
 * @return {string}
 */
openfl.system.Capabilities.get_os = function() {
  return null;
};


/**
 * @protected
 * @return {number}
 */
openfl.system.Capabilities.get_pixelAspectRatio = function() {
  return 0;
};


/**
 * @protected
 * @return {number}
 */
openfl.system.Capabilities.get_screenDPI = function() {
  return 0;
};


/**
 * @protected
 * @return {number}
 */
openfl.system.Capabilities.get_screenResolutionX = function() {
  return 0;
};


/**
 * @protected
 * @return {number}
 */
openfl.system.Capabilities.get_screenResolutionY = function() {
  return 0;
};


/**
 * @protected
 * @return {string}
 */
openfl.system.Capabilities.get_version = function() {
  return null;
};


/**
 * @export
 * @param {string} type
 * @return {boolean}
 */
openfl.system.Capabilities.hasMultiChannelAudio = function(type) {
  return false;
};


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.avHardwareDisable;


/**
  * @export
  * @type {string} */
openfl.system.Capabilities.cpuArchitecture;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasAccessibility;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasAudio;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasAudioEncoder;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasEmbeddedVideo;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasIME;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasMP3;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasPrinting;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasScreenBroadcast;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasScreenPlayback;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasStreamingAudio;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasStreamingVideo;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasTLS;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.hasVideoEncoder;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.isDebugger;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.isEmbeddedInAcrobat;


/**
  * @export
  * @type {string} */
openfl.system.Capabilities.language;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.localFileReadDisable;


/**
  * @export
  * @type {string} */
openfl.system.Capabilities.manufacturer;


/**
  * @export
  * @type {number} */
openfl.system.Capabilities.maxLevelIDC;


/**
  * @export
  * @type {string} */
openfl.system.Capabilities.os;


/**
  * @export
  * @type {number} */
openfl.system.Capabilities.pixelAspectRatio;


/**
  * @export
  * @type {string} */
openfl.system.Capabilities.playerType;


/**
  * @export
  * @type {string} */
openfl.system.Capabilities.screenColor;


/**
  * @export
  * @type {number} */
openfl.system.Capabilities.screenDPI;


/**
  * @export
  * @type {number} */
openfl.system.Capabilities.screenResolutionX;


/**
  * @export
  * @type {number} */
openfl.system.Capabilities.screenResolutionY;


/**
  * @export
  * @type {string} */
openfl.system.Capabilities.serverString;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.supports32BitProcesses;


/**
  * @export
  * @type {boolean} */
openfl.system.Capabilities.supports64BitProcesses;


/**
  * @export
  * @type {string} */
openfl.system.Capabilities.touchscreenType;


/**
  * @export
  * @type {string} */
openfl.system.Capabilities.version;
