/**
 * Generated by Apache Royale Compiler from /home/joshua/Development/Haxe/openfl/lib/openfl/events/IEventDispatcher.as
 * openfl.events.IEventDispatcher
 *
 * @fileoverview
 * @externs
 *
 * @suppress {checkTypes|accessControls}
 */

/** @const */
var openfl = {};
/** @const */
openfl.events = {};

/**
 * @interface
 */
openfl.events.IEventDispatcher = function() {
};
/**
 * @export
 * @param {string} type
 * @param {Function} listener
 * @param {boolean=} useCapture
 * @param {number=} priority
 * @param {boolean=} useWeakReference
 */
openfl.events.IEventDispatcher.prototype.addEventListener = function(type, listener, useCapture, priority, useWeakReference) {
};
/**
 * @export
 * @param {openfl.events.Event} event
 * @return {boolean}
 */
openfl.events.IEventDispatcher.prototype.dispatchEvent = function(event) {
};
/**
 * @export
 * @param {string} type
 * @return {boolean}
 */
openfl.events.IEventDispatcher.prototype.hasEventListener = function(type) {
};
/**
 * @export
 * @param {string} type
 * @param {Function} listener
 * @param {boolean=} useCapture
 */
openfl.events.IEventDispatcher.prototype.removeEventListener = function(type, listener, useCapture) {
};
/**
 * @export
 * @param {string} type
 * @return {boolean}
 */
openfl.events.IEventDispatcher.prototype.willTrigger = function(type) {
};