/* Royale Dependency List: */
/**
 * Generated by Apache Royale Compiler from /home/joshua/Development/Haxe/openfl/lib/openfl/utils/AssetManifest.as
 * openfl.utils.AssetManifest
 *
 * @fileoverview
 * @externs
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

/** @const */
var openfl = {};
/** @const */
openfl.utils = {};

/**
 * @constructor
 */
openfl.utils.AssetManifest = function() {
};


/**
 * @export
 * @param {string} path
 * @param {string=} id
 */
openfl.utils.AssetManifest.prototype.addBitmapData = function(path, id) {
};


/**
 * @export
 * @param {string} path
 * @param {string=} id
 */
openfl.utils.AssetManifest.prototype.addBytes = function(path, id) {
};


/**
 * @export
 * @param {string} name
 * @param {string=} id
 */
openfl.utils.AssetManifest.prototype.addFont = function(name, id) {
};


/**
 * @export
 * @param {Array} paths
 * @param {string=} id
 */
openfl.utils.AssetManifest.prototype.addSound = function(paths, id) {
};


/**
 * @export
 * @param {string} path
 * @param {string=} id
 */
openfl.utils.AssetManifest.prototype.addText = function(path, id) {
};
