/* Royale Dependency List: */
/**
 * Generated by Apache Royale Compiler from /home/joshua/Development/Haxe/openfl/lib/openfl/utils/AssetLibrary.as
 * openfl.utils.AssetLibrary
 *
 * @fileoverview
 * @externs
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

/** @const */
var openfl = {};
/** @const */
openfl.utils = {};

/**
 * @constructor
 */
openfl.utils.AssetLibrary = function() {
};


/**
 * @export
 * @param {openfl.utils.ByteArray} bytes
 * @param {string=} rootPath
 * @return {openfl.utils.AssetLibrary}
 */
openfl.utils.AssetLibrary.fromBytes = function(bytes, rootPath) {
  return null;
};


/**
 * @export
 * @param {string} path
 * @param {string=} rootPath
 * @return {openfl.utils.AssetLibrary}
 */
openfl.utils.AssetLibrary.fromFile = function(path, rootPath) {
  return null;
};


/**
 * @export
 * @param {openfl.utils.AssetManifest} manifest
 * @return {openfl.utils.AssetLibrary}
 */
openfl.utils.AssetLibrary.fromManifest = function(manifest) {
  return null;
};


/**
 * @export
 * @param {string} id
 * @return {openfl.display.MovieClip}
 */
openfl.utils.AssetLibrary.prototype.getMovieClip = function(id) {
  return null;
};


/**
 * @export
 * @param {openfl.utils.ByteArray} bytes
 * @param {string=} rootPath
 * @return {openfl.utils.Future}
 */
openfl.utils.AssetLibrary.loadFromBytes = function(bytes, rootPath) {
  return null;
};


/**
 * @export
 * @param {string} path
 * @param {string=} rootPath
 * @return {openfl.utils.Future}
 */
openfl.utils.AssetLibrary.loadFromFile = function(path, rootPath) {
  return null;
};


/**
 * @export
 * @param {openfl.utils.AssetManifest} manifest
 * @return {openfl.utils.Future}
 */
openfl.utils.AssetLibrary.loadFromManifest = function(manifest) {
  return null;
};


/**
 * @export
 * @param {string} id
 * @return {openfl.utils.Future}
 */
openfl.utils.AssetLibrary.prototype.loadMovieClip = function(id) {
  return null;
};
