/**
 * Generated by Apache Royale Compiler from /home/joshua/Development/Haxe/openfl/lib/openfl/display/IBitmapDrawable.as
 * openfl.display.IBitmapDrawable
 *
 * @fileoverview
 * @externs
 *
 * @suppress {checkTypes|accessControls}
 */

/** @const */
var openfl = {};
/** @const */
openfl.display = {};

/**
 * @interface
 */
openfl.display.IBitmapDrawable = function() {
};